import { Dimensions, Platform } from 'react-native';

const isAndroid = Platform.OS === 'android';
const SCREEN_WIDTH = Dimensions.get('screen').width;
const SCREEN_HEIGHT = Dimensions.get('screen').height;
const WINDOW_WIDTH = Dimensions.get('window').width;
const WINDOW_HEIGHT = Dimensions.get('window').height;

const COLORS = {
  white: '#FFFFFF',
  black: '#000000',
  grey: '#D3D3D3',
  red: '#E03C32',
  yellow: '#FFD301',
  green: '#7BB662',
};

const ICONS_EDIBILITY = {
  edible: { name: 'mushroom-outline', color: COLORS.green },
  conditionally_edible: { name: 'alert-rhombus', color: COLORS.yellow },
  poisonous: { name: 'mushroom-off-outline', color: COLORS.red },
  deadly: { name: 'skull-outline', color: COLORS.red },
};

// TODO: TRY WITH react-native-fs

const MODEL_IMAGES = [
  require('../assets/images/Agaricus_augustus.jpg'),
  require('../assets/images/Agaricus_xanthodermus.jpg'),
  require('../assets/images/Amanita_amerirubescens.jpg'),
  require('../assets/images/Amanita_augusta.jpg'),
  require('../assets/images/Amanita_brunnescens.jpg'),
  require('../assets/images/Amanita_calyptroderma.jpg'),
  require('../assets/images/Amanita_flavoconia.jpg'),
  require('../assets/images/Amanita_muscaria.jpg'),
  require('../assets/images/Amanita_persicina.jpg'),
  require('../assets/images/Amanita_phalloides.jpg'),
  require('../assets/images/Amanita_velosa.jpg'),
  require('../assets/images/Armillaria_mellea.jpg'),
  require('../assets/images/Armillaria_tabescens.jpg'),
  require('../assets/images/Artomyces_pyxidatus.jpg'),
  require('../assets/images/Bolbitius_titubans.jpg'),
  require('../assets/images/Boletus_pallidus.jpg'),
  require('../assets/images/Boletus_rex-veris.jpg'),
  require('../assets/images/Cantharellus_californicus.jpg'),
  require('../assets/images/Cantharellus_cinnabarinus.jpg'),
  require('../assets/images/Cerioporus_squamosus.jpg'),
  require('../assets/images/Chlorophyllum_brunneum.jpg'),
  require('../assets/images/Chlorophyllum_molybdites.jpg'),
  require('../assets/images/Clitocybe_nuda.jpg'),
  require('../assets/images/Coprinellus_micaceus.jpg'),
  require('../assets/images/Coprinopsis_lagopus.jpg'),
  require('../assets/images/Coprinus_comatus.jpg'),
  require('../assets/images/Crucibulum_laeve.jpg'),
  require('../assets/images/Cryptoporus_volvatus.jpg'),
  require('../assets/images/Daedaleopsis_confragosa.jpg'),
  require('../assets/images/Entoloma_abortivum.jpg'),
  require('../assets/images/Flammulina_velutipes.jpg'),
  require('../assets/images/Fomitopsis_mounceae.jpg'),
  require('../assets/images/Galerina_marginata.jpg'),
  require('../assets/images/Ganoderma_applanatum.jpg'),
  require('../assets/images/Ganoderma_curtisii.jpg'),
  require('../assets/images/Ganoderma_oregonense.jpg'),
  require('../assets/images/Ganoderma_tsugae.jpg'),
  require('../assets/images/Gliophorus_psittacinus.jpg'),
  require('../assets/images/Gloeophyllum_sepiarium.jpg'),
  require('../assets/images/Grifola_frondosa.jpg'),
  require('../assets/images/Gymnopilus_luteofolius.jpg'),
  require('../assets/images/Hericium_coralloides.jpg'),
  require('../assets/images/Hericium_erinaceus.jpg'),
  require('../assets/images/Hygrophoropsis_aurantiaca.jpg'),
  require('../assets/images/Hypholoma_fasciculare.jpg'),
  require('../assets/images/Hypholoma_lateritium.jpg'),
  require('../assets/images/Hypomyces_lactifluorum.jpg'),
  require('../assets/images/Ischnoderma_resinosum.jpg'),
  require('../assets/images/Laccaria_ochropurpurea.jpg'),
  require('../assets/images/Lacrymaria_lacrymabunda.jpg'),
  require('../assets/images/Lactarius_indigo.jpg'),
  require('../assets/images/Laetiporus_sulphureus.jpg'),
  require('../assets/images/Laricifomes_officinalis.jpg'),
  require('../assets/images/Leratiomyces_ceres.jpg'),
  require('../assets/images/Leucoagaricus_americanus.jpg'),
  require('../assets/images/Leucoagaricus_leucothites.jpg'),
  require('../assets/images/Lycogala_epidendrum.jpg'),
  require('../assets/images/Lycoperdon_perlatum.jpg'),
  require('../assets/images/Lycoperdon_pyriforme.jpg'),
  require('../assets/images/Mycena_haematopus.jpg'),
  require('../assets/images/Mycena_leaiana.jpg'),
  require('../assets/images/Omphalotus_illudens.jpg'),
  require('../assets/images/Omphalotus_olivascens.jpg'),
  require('../assets/images/Panaeolina_foenisecii.jpg'),
  require('../assets/images/Panaeolus_cinctulus.jpg'),
  require('../assets/images/Panaeolus_papilionaceus.jpg'),
  require('../assets/images/Panellus_stipticus.jpg'),
  require('../assets/images/Phaeolus_schweinitzii.jpg'),
  require('../assets/images/Phlebia_tremellosa.jpg'),
  require('../assets/images/Phyllotopsis_nidulans.jpg'),
  require('../assets/images/Pleurotus_ostreatus.jpg'),
  require('../assets/images/Pleurotus_pulmonarius.jpg'),
  require('../assets/images/Pluteus_cervinus.jpg'),
  require('../assets/images/Psathyrella_candolleana.jpg'),
  require('../assets/images/Pseudohydnum_gelatinosum.jpg'),
  require('../assets/images/Psilocybe_allenii.jpg'),
  require('../assets/images/Psilocybe_aztecorum.jpg'),
  require('../assets/images/Psilocybe_azurescens.jpg'),
  require('../assets/images/Psilocybe_caerulescens.jpg'),
  require('../assets/images/Psilocybe_cubensis.jpg'),
  require('../assets/images/Psilocybe_cyanescens.jpg'),
  require('../assets/images/Psilocybe_muliercula.jpg'),
  require('../assets/images/Psilocybe_neoxalapensis.jpg'),
  require('../assets/images/Psilocybe_ovoideocystidiata.jpg'),
  require('../assets/images/Psilocybe_pelliculosa.jpg'),
  require('../assets/images/Psilocybe_zapotecorum.jpg'),
  require('../assets/images/Retiboletus_ornatipes.jpg'),
  require('../assets/images/Sarcomyxa_serotina.jpg'),
  require('../assets/images/Schizophyllum_commune.jpg'),
  require('../assets/images/Stereum_ostrea.jpg'),
  require('../assets/images/Stropharia_ambigua.jpg'),
  require('../assets/images/Stropharia_rugosoannulata.jpg'),
  require('../assets/images/Suillus_americanus.jpg'),
  require('../assets/images/Suillus_luteus.jpg'),
  require('../assets/images/Suillus_spraguei.jpg'),
  require('../assets/images/Tapinella_atrotomentosa.jpg'),
  require('../assets/images/Trametes_betulina.jpg'),
  require('../assets/images/Trametes_gibbosa.jpg'),
  require('../assets/images/Trametes_versicolor.jpg'),
  require('../assets/images/Trichaptum_biforme.jpg'),
  require('../assets/images/Tricholoma_murrillianum.jpg'),
  require('../assets/images/Tricholomopsis_rutilans.jpg'),
  require('../assets/images/Tubaria_furfuracea.jpg'),
  require('../assets/images/Tylopilus_felleus.jpg'),
  require('../assets/images/Tylopilus_rubrobrunneus.jpg'),
  require('../assets/images/Volvopluteus_gloiocephalus.jpg'),
];

export {
  isAndroid,
  SCREEN_WIDTH,
  SCREEN_HEIGHT,
  WINDOW_WIDTH,
  WINDOW_HEIGHT,
  COLORS,
  ICONS_EDIBILITY,
  MODEL_IMAGES,
};
